/*
 * timeline.js : FILM.TIMELINE for OktoberFESB 2026, the storyboard as data (docs/storyboard.md).
 * 120 bpm, 36 s = 18 bars, 1920x1080 landscape at 24 fps.
 */
(function () {
  'use strict';
  const FILM = (window.FILM = window.FILM || {});

  FILM.TIMELINE = {
    title: 'OktoberFESB 2026',
    bpm: 120,
    duration: 36,
    fps: 24,
    width: 1920,
    height: 1080,
    shots: [
      { id: 'office-night', file: '01-office-night.js', start: 0, end: 2, mode: 'illustrated', post: 0.5, title: 'The night of the release',
        brief: 'Night office, the monitor test list turns green row by row on 8ths, slow push-in.' },
      { id: 'deploy', file: '02-deploy.js', start: 2, end: 4, mode: 'illustrated', post: 0.5, title: 'A bearded hand presses Deploy',
        brief: 'Hoodie sleeve and beard edge from the top; the finger hits DEPLOY on T 2.5; confetti; caption "Релиз FESB 9" on T 3.0.' },
      { id: 'release-beer', file: '03-release-beer.js', start: 4, end: 6, mode: 'illustrated', post: 0.5, title: 'Loading the party',
        brief: '"Загрузка праздника…" bar fills with beer, tips into a glass on T 5.0, foam fills the whole frame by T 6.0.' },
      { id: 'tap', file: '04-tap.js', start: 6, end: 8.5, mode: 'illustrated', post: 0.5, title: 'Out of the foam: the tap',
        brief: 'Foam drains to reveal the Spaten House tap and the hero Maß (G1); caption "2 октября · Spaten House" on T 7.0.' },
      { id: 'bp-message', file: '05-bp-message.js', start: 8.5, end: 10, mode: 'schematic', title: 'The mug is a message',
        brief: 'Blueprint of the hero mug at G1: "Сообщение создано", payload, header, id labels; queue box moves on T 9.5.' },
      { id: 'waitress', file: '06-waitress.js', start: 10, end: 12.5, mode: 'illustrated', post: 0.5, title: 'Ten mugs across the hall',
        brief: 'The waitress walks left to right with ten mugs through the hall and stops at G2.' },
      { id: 'bp-route', file: '07-bp-route.js', start: 12.5, end: 14, mode: 'schematic', title: 'Routing: delivered 10 of 10',
        brief: 'Blueprint of the waitress at G2 as a router, route line from the tap to the FESB table, counter to 10/10.' },
      { id: 'prost', file: '08-prost.js', start: 14, end: 16, mode: 'illustrated', post: 0.5, title: 'Pork knuckle and Prost!',
        brief: 'The knuckle lands on T 14.25, the hero mug on T 14.5, the clink and caption "Prost!" on T 15.0.' },
      { id: 'chef-enter', file: '09-chef-enter.js', start: 16, end: 18.5, mode: 'illustrated', post: 0.5, title: 'The music turns salsa: the chef',
        brief: 'Spotlight on the doorway: the bald, bearded chef gleams, ties the red bandana, two salsa steps.' },
      { id: 'salsa-shirts', file: '10-salsa-shirts.js', start: 18.5, end: 22.5, mode: 'illustrated', post: 0.5, title: 'Salsa and flying t-shirts',
        brief: 'The chef salsas down the aisle and throws all fifteen t-shirts on 8ths, T 18.5 to 22.0, caught one beat later.' },
      { id: 'jersey-wall', file: '11-jersey-wall.js', start: 22.5, end: 25, mode: 'illustrated', post: 0.5, title: 'A wall of nines',
        brief: 'Fifteen teammates in FESB jerseys (back row 8 standing, front row 7 crouching) turn in a wave on 16ths: "FESB 9" on every back.' },
      { id: 'foam-nine', file: '12-foam-nine.js', start: 25, end: 28, mode: 'illustrated', post: 0.5, title: 'The foam writes a 9',
        brief: 'The chef spins and the foam from his mug draws a huge 9 (G3), done on T 27.0.' },
      { id: 'mug-camera', file: '13-mug-camera.js', start: 28, end: 30.5, mode: 'illustrated', post: 0.5, title: 'The mug comes to the camera',
        brief: 'From G3 the chef pushes the mug into the camera until it fills the frame (G4).' },
      { id: 'lockup', file: '14-lockup.js', start: 30.5, end: 36, mode: 'illustrated', post: 0.5, title: 'OktoberFESB 2026',
        brief: 'Pull back from G4 to the full OktoberFESB 2026 lockup; "Prost!" sticker and "Релиз FESB 9" ribbon.' },
    ],
    cues: [
      { t: 0.0, kind: 'swell', note: 'Soft tuba pickup and pizzicato tick; night office' },
      { t: 0.0, kind: 'sfx', note: 'Test ticks: bright blips on 8ths T 0.0 to 1.75 rising C6 D6 E6 F6 G6 A6 B6 C7' },
      { t: 2.0, kind: 'swell', note: 'Polka groove starts underneath (tuba oom-pah, accordion offbeats)' },
      { t: 2.5, kind: 'hit', note: 'Deploy: deep thunk, crash cymbal, brass stab; confetti ticks on 16ths to T 3.0' },
      { t: 3.0, kind: 'sfx', note: 'Caption bell for "Релиз FESB 9"' },
      { t: 4.0, kind: 'sfx', note: 'Pour: filtered noise sweeping up to T 5.0, ratchet tick each 0.1 s' },
      { t: 5.0, kind: 'hit', note: 'Cork pop as the bar tips into a glass' },
      { t: 5.5, kind: 'swell', note: 'Foam fizz swelling into a whoosh to the cut' },
      { t: 6.0, kind: 'cut', note: 'Full polka band tutti, clarinet melody' },
      { t: 7.0, kind: 'sfx', note: 'Caption bell for "2 октября · Spaten House"' },
      { t: 8.0, kind: 'sfx', note: 'Glass ping, high sine 3.2 kHz with a short ring' },
      { t: 8.5, kind: 'cut', note: 'Digital sparkle (FM bell arpeggio) for the blueprint; label blips on 8ths' },
      { t: 9.5, kind: 'sfx', note: 'Queue slide blip' },
      { t: 10.0, kind: 'cut', note: 'Footsteps on beats as wooden thumps, glass clinks on 8ths between, to T 12.5' },
      { t: 12.75, kind: 'sfx', note: 'Ten rising blips on 16ths T 12.75 to 13.5' },
      { t: 13.75, kind: 'hit', note: 'Success chime, major triad arpeggio' },
      { t: 14.25, kind: 'hit', note: 'Pork knuckle lands: heavy wooden thud' },
      { t: 14.5, kind: 'sfx', note: 'Glass set down' },
      { t: 15.0, kind: 'hit', note: 'Prost clink: detuned glass pings, brass hey stab, cymbal' },
      { t: 15.5, kind: 'swell', note: 'Drum fill into the change' },
      { t: 16.0, kind: 'cut', note: 'Record scratch, then salsa: clave 3-2, congas, piano montuno, bass, brass' },
      { t: 16.25, kind: 'sfx', note: 'Head gleam shimmer' },
      { t: 18.5, kind: 'sfx', note: 'Fifteen t-shirt throws: short whoosh on each 8th T 18.5 to 22.0, cloth-flap catch on each 8th T 19.0 to 22.5, cowbell stays on the beat' },
      { t: 23.0, kind: 'sfx', note: 'Turn-around wave: eight brass stabs on 16ths T 23.0 to 23.875, rising' },
      { t: 24.0, kind: 'hit', note: 'Full brass hit on the wall of nines' },
      { t: 25.5, kind: 'swell', note: 'Rising whoosh glissando while the foam draws the 9, to T 27.0' },
      { t: 27.0, kind: 'hit', note: 'Sparkle hit and brass fall on the finished 9' },
      { t: 27.5, kind: 'swell', note: 'Snare roll into the polka reprise' },
      { t: 28.0, kind: 'cut', note: 'Polka reprise, full band' },
      { t: 30.0, kind: 'swell', note: 'Whoosh rising into the cut' },
      { t: 30.5, kind: 'hit', note: 'Crash and brass tutti on the logo' },
      { t: 32.0, kind: 'sfx', note: 'Letter slams on 16ths T 32.0 to 32.5 as tom hits' },
      { t: 33.0, kind: 'hit', note: 'Big Prost brass chord' },
      { t: 35.0, kind: 'hit', note: 'Final chord ringing out to 36.0' },
    ],
  };
})();
